// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAucviZ-oSowLgvZS_uq-eZCtMM5F-rS3g',
    appId: '1:286574562115:web:66aa8de44d440c18097df6',
    messagingSenderId: '286574562115',
    projectId: 'uas-diki',
    authDomain: 'uas-diki.firebaseapp.com',
    storageBucket: 'uas-diki.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5BCyjPS6VnGGUp4IcOaf4kIa5R-S66w',
    appId: '1:286574562115:android:f2fb2e2366f5ffcc097df6',
    messagingSenderId: '286574562115',
    projectId: 'uas-diki',
    storageBucket: 'uas-diki.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt1j6oZmgNavZIaBXr6rOfLh2aeTpA5EU',
    appId: '1:286574562115:ios:e3222303d081b6de097df6',
    messagingSenderId: '286574562115',
    projectId: 'uas-diki',
    storageBucket: 'uas-diki.firebasestorage.app',
    iosBundleId: 'com.example.uasDiki',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt1j6oZmgNavZIaBXr6rOfLh2aeTpA5EU',
    appId: '1:286574562115:ios:e3222303d081b6de097df6',
    messagingSenderId: '286574562115',
    projectId: 'uas-diki',
    storageBucket: 'uas-diki.firebasestorage.app',
    iosBundleId: 'com.example.uasDiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAucviZ-oSowLgvZS_uq-eZCtMM5F-rS3g',
    appId: '1:286574562115:web:1d2034ef2c923420097df6',
    messagingSenderId: '286574562115',
    projectId: 'uas-diki',
    authDomain: 'uas-diki.firebaseapp.com',
    storageBucket: 'uas-diki.firebasestorage.app',
  );
}
